
mt5_manager = MT5Manager()
mt5_manager.TIMEFRAME_M5 = TIMEFRAME_M5
mt5_manager.TIMEFRAME_H1 = TIMEFRAME_H1
mt5_manager.TIMEFRAME_H4 = TIMEFRAME_H4
mt5_manager.TRADE_ACTION_DEAL = TRADE_ACTION_DEAL
mt5_manager.ORDER_TYPE_BUY = ORDER_TYPE_BUY
mt5_manager.ORDER_TYPE_SELL = ORDER_TYPE_SELL
mt5_manager.ORDER_TIME_GTC = ORDER_TIME_GTC
mt5_manager.ORDER_FILLING_IOC = ORDER_FILLING_IOC
mt5_manager.TRADE_RETCODE_DONE = TRADE_RETCODE_DONE
